server:
  port: 8080
spring:
  mvc:
    pathmatch:
      matching-strategy: ant_path_matcher
  datasource:
    url: jdbc:mysql://192.168.10.100:3306/mall?useUnicode=true&characterEncoding=utf-8&serverTimezone=Asia/Shanghai&useSSL=false
    username: root
    password: root
    druid:
      initial-size: 5 #连接池初始化大小
      min-idle: 10 #最小空闲连接数
      max-active: 20 #最大连接数
      web-stat-filter:
        exclusions: "*.js,*.gif,*.jpg,*.png,*.css,*.ico,/druid/*" #不统计这些请求数据
      stat-view-servlet: #访问监控网页的登录用户名和密码
        login-username: druid
        login-password: druid
  redis:
    host: 192.168.10.100 # Redis服务器地址
    database: 0 # Redis数据库索引（默认为0）
    port: 6379 # Redis服务器连接端口
    password:  # Redis服务器连接密码（默认为空）
    timeout: 3000ms # 连接超时时间（毫秒）
  rabbitmq: #rabbitmq相关配置
    host: 192.168.10.100
    port: 5672
    username: guest
    password: guest
  servlet:
    multipart:
      enabled: true #开启文件上传
      max-file-size: 10MB #限制文件上传大小为10M
mybatis:
  mapper-locations:
    - classpath:dao/*.xml
    - classpath*:com/**/mapper/*.xml
management: #开启SpringBoot Admin的监控
  endpoints:
    web:
      exposure:
        include: '*'
  endpoint:
    health:
      show-details: always
redis:
  database: mall
  key:
    admin: 'ums:admin'
  expire:
    common: 86400 # 24小时
aliyun:
  oss:
    endpoint: oss-cn-beijing.aliyuncs.com # oss对外服务的访问域名
    accessKeyId: LTAI5t9KZbwXWrJbZzVD3dov # 访问身份验证中用到用户标识
    accessKeySecret: oxufTijTHSXsDtRChihomsIfQSLa3N # 用户用于加密签名字符串和oss用来验证签名字符串的密钥
    bucketName: sigma429-oss # oss的存储空间
    policy:
      expire: 300 # 签名有效期(S)
    maxSize: 10 # 上传文件大小(M)
    callback: https://b095-240e-324-850e-ea00-88fa-f17f-a8c6-29f1.ngrok-free.app/aliyun/oss/callback # 文件上传成功后的回调地址,ip必须为公网ip
    dir:
      prefix: mall/images/ # 上传文件夹路径前缀
minio:
  endpoint: http://192.168.10.100:9090 #MinIO服务所在地址
  bucketName: mall #存储桶名称
  accessKey: minioadmin #访问的key
  secretKey: minioadmin #访问的秘钥
feign:
  okhttp:
    enabled: true
  client:
    config:
      default:
        connectTimeout: 5000
        readTimeout: 5000
        loggerLevel: basic
#logging:
#  pattern:
#    dateformat: yyyy-MM-dd HH:mm:ss.SSS
#  file:
#    name: logging.log
#  logback:
#    rollingpolicy:
#      file-name-pattern: ${LOG_FILE}.%d{yyyy-MM-dd}.%i.gz
#      max-file-size: 100MB
#      max-request-size: 100MB